apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- route.yaml

commonLabels:
  app: waver-site
  part-of: waver-site
