apiVersion: v1
kind: Secret
metadata:
  name: waver-site-secrets
  labels:
    app: waver-site
type: Opaque
data:
  # These are base64 encoded values - replace with your actual values
  # echo -n "your-access-key" | base64
  minio-access-key: bWluaW9hZG1pbg==
  # echo -n "your-secret-key" | base64
  minio-secret-key: bWluaW9hZG1pbg==
