services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BUCKETS: elastic-bucket  # init with bucket
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    command: server /data --console-address ":9001"