name: Build and Push to Quay.io

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'waver-site/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'waver-site/**'

env:
  QUAY_NAMESPACE: sshaaf
  IMAGE_NAME: waver-site
  QUAY_REPOSITORY: quay.io/sshaaf/waver-site

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: waver-site

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get Git SHA
      id: git-sha
      run: |
        echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "full-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Log in to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./waver-site
        push: true
        tags: |
          ${{ env.QUAY_REPOSITORY }}:${{ steps.git-sha.outputs.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

    - name: Output image info
      run: |
        echo "✅ Successfully built and pushed image:"
        echo "   Repository: ${{ env.QUAY_REPOSITORY }}"
        echo "   Tag: ${{ steps.git-sha.outputs.sha }}"
        echo "   Full SHA: ${{ steps.git-sha.outputs.full-sha }}"
        echo "   Image URL: ${{ env.QUAY_REPOSITORY }}:${{ steps.git-sha.outputs.sha }}"
