---
name: Build and Push Backend

on:
  push:
    branches: [main, fix-actions]
    paths:
      - 'waver-backend/**'
      - '.github/workflows/backend-build-and-push.yml'
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.jpg'
  pull_request:
    branches: [main, fix-actions]
    paths:
      - 'waver-backend/**'
      - '.github/workflows/backend-build-and-push.yml'
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.jpg'
  workflow_dispatch:

env:
  QUAY_REPOSITORY: quay.io/sshaaf/waver-backend

jobs:
  build-and-push:
    environment: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-backend-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-backend-

      - name: Log in to Quay.io
        # This step is safe to run for both events.
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build Container Image (PR Check)
        # This step ONLY runs for pull requests.
        # It builds the image but does NOT push.
        if: github.event_name == 'pull_request'
        working-directory: ./waver-backend
        run: |
          mvn package \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=false \
            -Dquarkus.container-image.tag=${{ github.sha }}

      - name: Build and Push Container Image (on Merge to Main)
        # This step ONLY runs on a push to the main branch.
        # It builds AND pushes.
        if: github.event_name == 'push'
        working-directory: ./waver-backend
        run: |
          mvn package \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.tag=${{ github.sha }} \
            -Dquarkus.container-image.additional-tags=latest
