name: Build and Push Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'waver-backend/**'
      - '.github/workflows/backend-build-and-push.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'waver-backend/**'
      - '.github/workflows/backend-build-and-push.yml'

  workflow_dispatch:

env:
  IMAGE_NAME: quay.io/sshaaf/waver-backend

jobs:
  build-and-push:
    environment: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      # Set up Docker Buildx with the docker-container driver to enable GHA cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          
      - name: Build Container Image (PR Check)
        if: github.event_name == 'pull_request'
        working-directory: ./waver-backend
        run: |
          mvn package \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=false \
            -Dquarkus.container-image.tag=${{ github.sha }}

      - name: Build and Push Container Image (Main Branch)
        if: github.event_name == 'push'
        working-directory: ./waver-backend
        run: |
          mvn package \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.tag=${{ github.sha }} \
            -Dquarkus.container-image.additional-tags=latest
